
name: food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  curved_navigation_bar: ^1.0.6
  fluttertoast: ^8.0.9
  http: ^1.2.2
  image_picker: ^1.1.2
  file_picker: ^9.2.2
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  random_string: ^2.3.1
  provider: ^6.1.4
  mysql1: ^0.20.0
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  
  # Bỏ dòng này
  # - images/profile_placeholder.png
  
    # Thêm các ảnh khác nếu cần

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf